name: Branch for UPM
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    name: split upm branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git subtree split -P "$PKG_ROOT" -b upm
        git push -u origin upm
      env:
        PKG_ROOT: Packages/com.calci.assetlens
